CREATE DATABASE safegrid_apriori_data;

CREATE TABLE `DataDeck_Apriori` (
  `id`  INT AUTO_INCREMENT PRIMARY KEY,
  `flow_psh` float DEFAULT NULL,
  `fpkts_per_second` float DEFAULT NULL,
  `total_bhlen` float DEFAULT NULL,
  `flow_iat_max` float DEFAULT NULL,
  `backward_packet_length_max` float DEFAULT NULL,
  `forward_iat_std` float DEFAULT NULL,
  `total_length_of_forward_packets` float DEFAULT NULL,
  `backward_packet_length_std` float DEFAULT NULL,
  `forward_iat_min` float DEFAULT NULL,
  `total_fhlen` float DEFAULT NULL,
  `total_length_of_backward_packets` float DEFAULT NULL,
  `total_backward_packets` float DEFAULT NULL,
  `forward_iat_max` float DEFAULT NULL,
  `forward_packet_length_mean` float DEFAULT NULL,
  `backward_iat_min` float DEFAULT NULL,
  `flow_iat_min` float DEFAULT NULL,
  `backward_packet_length_min` float DEFAULT NULL,
  `flow_syn` float DEFAULT NULL,
  `bpkts_per_second` float DEFAULT NULL,
  `flow_protocol` float DEFAULT NULL,
  `forward_iat_total` float DEFAULT NULL,
  `forward_packet_length_min` float DEFAULT NULL,
  `backward_iat_max` float DEFAULT NULL,
  `flow_iat_total` float DEFAULT NULL,
  `flow_urg` float DEFAULT NULL,
  `flow_fin` float DEFAULT NULL,
  `flow_ece` float DEFAULT NULL,
  `forward_packet_length_std` float DEFAULT NULL,
  `backward_packet_length_mean` float DEFAULT NULL,
  `flow_iat_std` float DEFAULT NULL,
  `flow_ack` float DEFAULT NULL,
  `backward_iat_total` float DEFAULT NULL,
  `backward_iat_mean` float DEFAULT NULL,
  `flow_rst` float DEFAULT NULL,
  `total_forward_packets` float DEFAULT NULL,
  `flow_packets_per_second` float DEFAULT NULL,
  `backward_iat_std` float DEFAULT NULL,
  `flow_cwr` float DEFAULT NULL,
  `forward_iat_mean` float DEFAULT NULL,
  `flow_iat_mean` float DEFAULT NULL,
  `forward_packet_length_max` float DEFAULT NULL,
  `reconnaissance` float DEFAULT NULL,
  `infection` float DEFAULT NULL,
  `action` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3

GRANT ALL PRIVILEGES ON safegrid_apriori_data.* TO 'SafeGrid'@'localhost';
FLUSH PRIVILEGES;